# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-11-13

    - name: Cache cargo
      uses: Swatinem/rust-cache@v2
      with:
        workspaces:
            "cairoVM/juno/vm/rust -> target"
            "cairoVM/juno/core/rust -> target"
            "cairoVM/juno/starknet/rust -> target"

    - name: Download juno
      run: |
        git submodule init
        git submodule update --recursive --checkout

    - name: Build
      run: make build

#    - name: Test
#      run: go test -v ./...
